spring:
  application:
    name: employee-management-system

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_APP_USER}
    password: ${DB_APP_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true

  flyway:
    enabled: true
    schemas: public, auth
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    
server:
  port: 8080

jwt:
  secret: ${APP_JWT_SECRET}
  expiration-ms: ${APP_JWT_EXPIRATION_MS}