spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false

  flyway:
    clean-disabled: true
    baseline-on-migrate: false

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  error:
    include-message: never