version: '3.9'
services:
  postgres:
    image: postgres:18-alpine
    container_name: ems-db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ems_db
    ports:
      - "5432:5432"
    volumes:
      - ems_db_data:/var/lib/postgresql/data
volumes:
  ems_db_data:
