#!/bin/bash
set -e

# 1. Sicherstellen, dass die DB existiert (Idempotent)
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    SELECT 'CREATE DATABASE $POSTGRES_DB' 
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB')\gexec
EOSQL

# 2. User anlegen und Schemas initialisieren
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    DO \$$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$DB_APP_USER') THEN
        CREATE USER $DB_APP_USER WITH PASSWORD '$DB_APP_PASSWORD';
      END IF;
    END \$$;

    CREATE SCHEMA IF NOT EXISTS auth;
    
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $DB_APP_USER;
    GRANT USAGE, CREATE ON SCHEMA public TO $DB_APP_USER;
    GRANT USAGE, CREATE ON SCHEMA auth TO $DB_APP_USER;

    -- Berechtigungen für alle Objekttypen (Public & Auth)
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $DB_APP_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $DB_APP_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO $DB_APP_USER;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO $DB_APP_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO $DB_APP_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON FUNCTIONS TO $DB_APP_USER;

    ALTER SCHEMA public OWNER TO $DB_APP_USER;
    ALTER SCHEMA auth OWNER TO $DB_APP_USER;
EOSQL