-- 1. DEPARTMENT
CREATE TABLE IF NOT EXISTS public.department (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    version    BIGINT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. PROJECT (Muss vor employee_project kommen)
CREATE TABLE IF NOT EXISTS public.project (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 3. EMPLOYEE
CREATE TABLE IF NOT EXISTS public.employee (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(45)  NOT NULL,
    last_name     VARCHAR(45)  NOT NULL,
    email         VARCHAR(100) NOT NULL UNIQUE,
    department_id BIGINT NOT NULL,
    version       BIGINT DEFAULT 0 NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_employee_department FOREIGN KEY (department_id) 
        REFERENCES public.department(id) ON DELETE RESTRICT  -- ✅ GEÄNDERT
);

-- 4. EMPLOYEE_PROJECT (Join Table)
CREATE TABLE IF NOT EXISTS public.employee_project (
    employee_id BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    PRIMARY KEY (employee_id, project_id),
    CONSTRAINT fk_employee FOREIGN KEY (employee_id) 
        REFERENCES public.employee(id) ON DELETE CASCADE,
    CONSTRAINT fk_project  FOREIGN KEY (project_id)  
        REFERENCES public.project(id)  ON DELETE CASCADE
);

-- 5. EMPLOYEE_PROFILE (One-to-One)
CREATE TABLE IF NOT EXISTS public.employee_profile (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL UNIQUE,
    bio         TEXT,
    phone       VARCHAR(20),
    address     TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_profile_employee FOREIGN KEY (employee_id) 
        REFERENCES public.employee(id) ON DELETE CASCADE
);

